[package]
name = "dist-iter"
version = "0.1.0"
edition = "2021"

[dependencies]
linkme = "0.3.22"
mpi = { version = "0.7.0", features = ["derive", "user-operations"] }
dist-iter-macros = { path = "../dist-iter-macros" }
